# -*- coding: utf-8 -*-
"""code3.3_LinearSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kguQ91dGYX8JNJsVoBJpXdMW_hebGl9O
"""

import math

# 全探索で最小値を求める
def linear_search(N: int):
    """
    input:
    N:int, 探索する配列の長さ
    output:
    min_value:int, 最小値
    """
    # 探索対象のリストを作成
    object_list = []
    for i in range(N):
        num = int(input())
        object_list.append(num)
    # 探索
    min_value = math.inf
    for i in range(N):
        if object_list[i] < min_value:
            min_value = object_list[i]
    return min_value

linear_search(5)