# -*- coding: utf-8 -*-
"""code3.1_LinearSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7c0hEVDgkbjPTkZWdNFC5rDxpShHTvy
"""

def linear_search(N: int, v: int):
    """
    input:
    N:int, 探索する配列の長さ
    v:int, 存在するか調べる値
    output:
    'Yes.', 存在する場合
    'No.', 存在しない場合
    """
    # 探索対象のリストを作成
    object_list = []
    for i in range(N):
        num = int(input())
        object_list.append(num)
    # 探索
    exist = False
    for i in range(N):
        if object_list[i] == v:
            exist = True
            break
    if exist == True:
        print('Yes.')
    else: print('No.')

# test
linear_search(3, 2)

linear_search(10, 4)