# -*- coding: utf-8 -*-
"""code3.2_LinearSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFKfpNiMsjp1C0hOkfIdbaQeauzpTM9K
"""

def linear_search(N: int, v: int):
    """
    input:
    N:int, 探索する配列の長さ
    v:int, 存在するか調べる値
    output:
    found_id:int, 存在しないときは-1、存在するときはその添字
    """
    # 探索対象のリストを作成
    object_list = []
    for i in range(N):
        num = int(input())
        object_list.append(num)
    # 探索
    found_id = -1
    for i in range(N):
        if object_list[i] == v:
            found_id = i
            break
    return found_id

# test
linear_search(3,2)